jaime.pdf: UEM_THESIS_JAIME_BOWEN.tex
	pdflatex UEM_THESIS_JAIME_BOWEN.tex 
.PHONY: clean
clean:
	-rm -f *.aux
	-rm -f *.log
	-rm -f *.toc
	-rm -f *.bbl
	-rm -f *.blg
	-rm -f *.out
	-rm -f *.loc
	-rm -f *.soc
